# Import other configs.
import = ['~/.config/alacritty/keybinds.toml']

[colors]
primary={ background="#000000" }

[env]
TERM="alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
dynamic_padding=false
decorations="Full"
opacity=0.8
padding={x = 5, y = 0}

[scrolling]
multiplier=3
