# Import other configs.
import = ['~/.config/alacritty/keybinds.toml']
live_config_reload = true

[shell]
program = "/usr/bin/tmux"
args = ['new-session']

[colors]
primary={ background="#000000" }

[window]
dynamic_padding=false
decorations="None"
opacity=0.8
padding={x = 0, y = 0}
startup_mode="Maximized"

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
size = 12

[scrolling]
multiplier=5
