# Import other configs.
import = ['~/.config/alacritty/keybinds.toml']

[shell]
program = "/usr/bin/tmux"
args = ['new-session']

[colors]
primary={ background="#000000" }

[env]
TERM="alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
dynamic_padding=false
decorations="None"
opacity=0.8
padding={x = 0, y = 0}
startup_mode="Maximized"

[font]
normal.family = "Noto Sans Mono"
size = 10.5

[scrolling]
multiplier=5
