#!/bin/bash

# check if $HOME and $XDG_CONFIG_HOME are present.
if [[ -z $HOME ]] then
  echo "[env] \$HOME is not present as an env var. you gotta set the home dir before running this."
  exit 1
fi

# install some useful programs.
function ensure_programs() {
  local programs="ripgrep,git,stow,zsh,tmux"
  for program in ${programs//,/ }
  do
    if ! dpkg -l | grep -q $program; then
      echo "[config] $program is not found, installing..."
      sudo apt-get install $program
    else
      echo "[config] $program found, skipping install..."
    fi
  done
}
# place config files.
function stow_config_files() {\
  local stow_folders="zsh,nvim,alacritty,home,tmux"
  for folder in ${stow_folders//,/ }
  do
    if [[ $folder == "zsh" || $folder == "home" ]]; then # except for zsh and home, treat every other folder for .config
      echo "[config] linking $folder/* to $HOME."
      stow -t $HOME $folder
    else
      if [[ ! -d $HOME/.config/$folder ]]; then
        mkdir $HOME/.config/$folder
      fi
      echo "[config] linking $folder/* to $HOME/.config/$folder."
      stow -t $HOME/.config/$folder $folder
    fi
  done
}
# ensure packer is installed
function setup_packer() {
  local packer_path="$DOT_LOCAL/share/nvim/site/pack/packer/start/packer.nvim"
  if [[ ! -d ${packer_path} ]]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim ${packer_path}
    echo "[config] Installed packer for nvim on ${packer_path}"
  fi
}

ensure_programs
stow_config_files
setup_packer
tmux source ~/.config/tmux/tmux.conf
echo "[config] done. :3"
