#!/usr/bin/zsh

if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="zsh"
fi

if [[ -z $DOTFILES ]]; then
    export DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Stowing $folder"
  stow -D $folder
  stow $folder
done
popd
